### ISSUE TITLE
Cleanup LFS data

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/opentelemetry-agent-metrics-plugin#6]
Hey @christophe-kamphaus-jemmic,

GitHub reported that your repository drains and exceeds the entire LFS quota for the jenkinsci organization:

![Screenshot 2023-08-26 at 16 55 30](https://github.com/jenkinsci/opentelemetry-agent-metrics-plugin/assets/13383509/89f6b397-695b-478c-8977-3ae656254dec)

According to https://github.com/jenkinsci/opentelemetry-agent-metrics-plugin/blob/7743ac9c0c70ad5815b917acf0c409964ec1df7e/.gitattributes#L5-L19, you store various large files in LFS.

Could you clean up the files from the git history please?

Thanks in advance!

**Comment by christophe-kamphaus-jemmic** [comment]
> GitHub reported that your repository drains and exceeds the entire LFS quota for the jenkinsci organization

Sorry about that.

> Could you clean up the files from the git history please?

Done, I've rewritten the history (including all tags) to remove all LFS files, which was quite painful.

Unfortunately according to https://docs.github.com/en/repositories/working-with-files/managing-large-files/removing-files-from-git-large-file-storage#git-lfs-objects-in-your-repository this might not be enough to remove these files from Github LFS remote storage.

If the repository needs to be recreated what would be the best way forward?

**Comment by NotMyFault** [comment]
> Done, I've rewritten the history (including all tags) to remove all LFS files, which was quite painful.

Thanks for your swift response! Unfortunately, GitHub updates LFS quotas every 30 days only, and we don't see an immediate effect.

With your permissions, I'd recreate the GitHub repository if that's needed to completely wipe the LFS data from GitHub's end. That should lead to great avail, given you've rewritten the history already.

**Comment by christophe-kamphaus-jemmic** [comment]
> With your permissions, I'd recreate the GitHub repository if that's needed to completely wipe the LFS data from GitHub's end. That should lead to great avail, given you've rewritten the history already.

Fine with me. Go ahead.

**Comment by NotMyFault** [comment]
> > With your permissions, I'd recreate the GitHub repository if that's needed to completely wipe the LFS data from GitHub's end. That should lead to great avail, given you've rewritten the history already.
> 
> Fine with me. Go ahead.

All done. 

![Screenshot 2023-08-28 at 09 04 38](https://github.com/jenkinsci/opentelemetry-agent-metrics-plugin/assets/13383509/c7275575-9d7b-48d7-99a0-7a20ddb80945)

Storage quota is down to the usual amount. 

Thanks!
